[package]
name = "line_to_equation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.8"
libm = "0.2.8"
num = "0.4.1"
rand = "0.8.5"
rustfft = "6.1.0"
